---
- name: Running PMM Data Container without Security ( unprotected )
  docker:
    name: pmm-server
    insecure_registry: true
    image: "{{ pmm_server_image_repo }}/{{pmm_server_image_name }}:{{ pmm_server_version }}"
    state: started
    volumes_from:
    - pmm-data
    ports:
    - "80:80"
    restart_policy: always
